[target.x86_64-unknown-linux-musl]
pre-build = [
    "apt-get update",
    "apt-get --assume-yes install curl",
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get --assume-yes install nodejs"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "apt-get update",
    "apt-get --assume-yes install curl",
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get --assume-yes install nodejs"
]

[target.x86_64-pc-windows-gnu]
pre-build = [
    "apt-get update",
    "apt-get --assume-yes install curl",
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get --assume-yes install nodejs"
]

[target.x86_64-apple-darwin]
image = "ghcr.io/cross-rs/x86_64-apple-darwin-cross:local"
pre-build = [
    "apt-get update",
    "apt-get --assume-yes install curl",
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get --assume-yes install nodejs"
]

[target.aarch64-apple-darwin]
image = "ghcr.io/cross-rs/aarch64-apple-darwin-cross:local"
pre-build = [
    "apt-get update",
    "apt-get --assume-yes install curl",
    "curl -fsSL https://deb.nodesource.com/setup_20.x | bash -",
    "apt-get --assume-yes install nodejs"
]
