version: '3'

services:
  ffplayout:
    container_name: ffplayout
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/db:/db
      - ./data/storage:/tv-media
      - ./data/playlists:/playlists
      - ./data/logging:/logging
      - ./data/public:/public
    ports:
      - '8787:8787'
